FitnessCenter_Project/Controllers/CoachController.cs
using FitnessCenter_Project.Service;
using FitnessCenterModel;
using FitnessCenterModel.DTO;
using FitnessCenterModel.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FitnessCenter_Project.Controllers
{
    public class CoachController : baseController
    {
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult RegisterCoach(RegisterCoachViewModel model)
        {
            RegisterSerivce service = new RegisterSerivce();
            RegisterResult result = service.RegisterCoach(model);
            return Json(new { success = result.ReturnNo == 1 ? true : false, ex = result.Message },
                             JsonRequestBehavior.AllowGet);
        }
        public ActionResult UpdateCoach()
        {
            UpdateService service = new UpdateService();
            UpdateCoachViewModel model = new UpdateCoachViewModel();
            if (LoginState)
            {
                string City = string.Empty;
                string Area = string.Empty;
                string Address = string.Empty;
                User user = GetMemberInfo();
                string MemberId = user.MemberId;
                UpdateCoach updateModel = service.GetCoachInfo(MemberId);
                string[] AddressArray = updateModel.User.Address.Split('|');
                if (AddressArray.Length == 3)
                {
                    City = AddressArray[0];
                    Area = AddressArray[1];
                    updateModel.User.Address = AddressArray[2];
                }

                model.addressCityList = new SelectList(service.GetCity(City), "Value", "Text");
                model.addresAreaList = new SelectList(service.GetArea(), "Value", "Text", Area);
                model.AreaList = new MultiSelectList(service.GetCity(updateModel.OriginArea.ToArray()), "Value", "Text", updateModel.OriginArea);
                model.CourseList = new MultiSelectList(service.GetCourse(updateModel.OriginCourse.ToArray()), "Value", "Text", updateModel.OriginCourse);
                model.TrainingProgramList= new MultiSelectList(service.GetTrainingProgram(updateModel.OriginTrainProgram.ToArray()), "Value", "Text", updateModel.OriginTrainProgram);
                
                model.UpdateModel = updateModel;
                

            }
            else
                return RedirectToAction("Login", "Home");
            
            return View(model);
        }
        [HttpPost]
        public ActionResult UpdateCoach(UpdateCoachViewModel model)
        {
            UpdateService service = new UpdateService();
            Result result = service.UpdateCoach(model);

            return Json(new { success = result.ReturnNo == 1 ? true : false, ex = result.Message },
                  JsonRequestBehavior.AllowGet);
        }

    }
}

FitnessCenter_Project/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FitnessCenterModel;
using FitnessCenter_Project.Service;
using FitnessCenterModel.DTO;
using System.Net.Http;
using Newtonsoft.Json;
using System.Text;
using System.Web.Security;
using FitnessCenterModel.ViewModel;
using System.IO;

namespace FitnessCenter_Project.Controllers
{
    public class MemberController : baseController
    {
        
        public ActionResult Register()
        {
            return View();
        }
        //ajax方法
        [HttpPost]
        public ActionResult RegisterMember(RegisterMebmberViewModel model)
        {
            RegisterSerivce service = new RegisterSerivce();
            RegisterResult result = service.RegisterMember(model);
            return Json(new { success = result.ReturnNo==1? true:false,ex=result.Message },
                 JsonRequestBehavior.AllowGet);
        }

        public ActionResult UpdateMember()
        {
            UpdateService service = new UpdateService();
            UpdateMemberViewModel model = new UpdateMemberViewModel();
            //檢查是否登入狀態
            if (LoginState)
            {
                string City = string.Empty;
                string Area = string.Empty;
                string Address = string.Empty;
                User user = GetMemberInfo();
                string MemberId = user.MemberId;

                UpdateMember updatemodel = service.GetMemberInfo(MemberId);
                string[] AddressArray = updatemodel.User.Address.Split('|');
                if (AddressArray.Length == 3)
                {
                     City = AddressArray[0];
                     Area = AddressArray[1];
                    updatemodel.User.Address = AddressArray[2];
                }
                
                
                model.addressCity = City;
                model.addressArea = Area;
                model.addressCityList = new SelectList(service.GetCity(City), "Value", "Text");
                model.addresAreaList = new SelectList(service.GetArea(), "Value", "Text", Area);
                model.AreaList = new MultiSelectList(service.GetCity(updatemodel.OriginArea.ToArray()), "Value", "Text", updatemodel.OriginArea);
                model.UpdateModel = updatemodel;

            }
            else
               return RedirectToAction("Login", "Home");


            return View(model);

        }
        //ajax方法
        [HttpPost]
        public ActionResult UpdateMember(UpdateMemberViewModel model)
        {
            UpdateService service = new UpdateService();
            Result result = service.UpdateMember(model);

            return Json(new { success = result.ReturnNo == 1 ? true : false, ex = result.Message },
                  JsonRequestBehavior.AllowGet);
        }

        



    }
}

FitnessCenter_Project/Controllers/ReserveController.cs
using FitnessCenter_Project.Service;
using FitnessCenterModel;
using FitnessCenterModel.DTO;
using FitnessCenterModel.Para;
using FitnessCenterModel.ViewModel;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FitnessCenter_Project.Controllers
{
    public class ReserveController : baseController
    {
        //預約面談
        public ActionResult ReserveInterveiw(string CoachId,string CoachName)
        {
            ReserveInterviewModel model = new ReserveInterviewModel();
            if (LoginState)
            {
                User member = GetMemberInfo();
                InteriewPara para = new InteriewPara()
                {
                    CoachId = CoachId,
                    MemberId = member.MemberId,
                    ReserveDate = DateTime.Now
                };
                model.Para = para;
                model.CoachName = CoachName;
                return View(model);
            }
            else
                return RedirectToAction("Login", "Home");
            
                
        }
        //ajax
        [HttpPost]
        public ActionResult ReserveInterveiw(ReserveInterviewModel model)
        {
            
            var result = ReserveService.Instance.reserveInterview(model.Para);
            return Json(new { success = result.ReturnNo == 1 ? true : false, ex = result.Message },
                 JsonRequestBehavior.AllowGet);
        }
        //預約服務
        public ActionResult ReserveClass(string CoachId,string CoachName)
        {
            ReserveServiceModel model = new ReserveServiceModel();
            
            if (LoginState)
            {
                User member = GetMemberInfo();
                SearchService search = new SearchService();
                Coach coach = search.GetCoachDetail(CoachId);
                ServicePara para = new ServicePara()
                {
                    CoachId = CoachId,
                    MemberId = member.MemberId,
                    ServiceDate = DateTime.Now,
                    Location = coach.Address.Replace("|", "")//預設教練地址
                };
                model.Para = para;
                model.CoachName = CoachName;
                
                //教練有服務的項目
                var trainprogrem= ReserveService.Instance.GetCoachTraingProgramList(coach.TrainingProgramId.ToArray());
                var course = ReserveService.Instance.GetCoachCourseList(coach.CourseId.ToArray());
                model.TrainProgramList = new SelectList(trainprogrem, "Value", "Text");
                model.CourseList = new SelectList(course, "Value", "Text");
                return View(model);
            }
            else
                return RedirectToAction("Login", "Home");




            
        }
        [HttpPost]
        public ActionResult ReserveClass(ReserveServiceModel model)
        {
            
            var result = ReserveService.Instance.reserveClass(model.Para);
            return Json(new { success = result.ReturnNo == 1 ? true : false, ex = result.Message },
                 JsonRequestBehavior.AllowGet);

        }

        //預約服務/面談 檢視
        public ActionResult OrderList()
        {
            
            if (LoginState)
            {
                User member = GetMemberInfo();
                OrderListModel model = new OrderListModel() {
                    inserview= ReserveService.Instance.SearchInterview(member.MemberId,member.State),
                    service= ReserveService.Instance.SearchService(member.MemberId, member.State),
                    State=member.State
                };



                return View(model);
            }
            else
                return RedirectToAction("Login", "Home");

            
        }
        #region 檢視面談
        //教練檢視
        public ActionResult CoachInterViewDetail(int OrderId=1)
        {
            
            int[] status =new int[] { 1, 2, 4, 6};//DB定義的Status ID
            string[] disabled = new string[] { "6" };
            if (LoginState)
            {
                User member = GetMemberInfo();
                Interview interview = ReserveService.Instance.SearchInterview(member.MemberId, member.State)
                    .Where(c=>c.OrderId.Equals(OrderId)).FirstOrDefault();
                var statusList= ReserveService.Instance.OrderStatusList(interview.StatusId, status);
               var model = new InterViewDetailModel()
                {
                    StatusList = new SelectList(statusList, "Value", "Text", interview.StatusId, disabled),
                    interview = interview,
                   
               };
                return View(model);
            }
            else
                return RedirectToAction("Login", "Home");
            
        }
        //會員檢視
        public ActionResult MemberInterViewDetail(int OrderId=1)
        {
            
            int[] types = new int[] { 1, 2, 4, 6};
            if (LoginState)
            {
                User member = GetMemberInfo();
                
                Interview interview = ReserveService.Instance.SearchInterview(member.MemberId, member.State)
                    .Where(c => c.OrderId.Equals(OrderId)).FirstOrDefault();
                var status = ShareService.Instance.GetReserveStatus().Where(c => types.Contains(c.ID)).ToList();
                InterviewDetail model = new InterviewDetail() {
                    interview=interview,
                    Status= status

                };

                return View(model);
            }
            else
                return RedirectToAction("Login", "Home");
            
        }
        //更新面談狀態
        [HttpPost]
        public ActionResult UpdateInterview(UpdateInterview para)
        {
            
            var result = ReserveService.Instance.UpdateInterviewOrder(para);
            return Json(new { success = result.ReturnNo == 1 ? true : false, ex = result.Message },
                 JsonRequestBehavior.AllowGet);

        }
        #endregion

        #region 檢視服務
        //教練檢視
        public ActionResult CoachServiceDatail(int OrderId=5)
        {
            
            int[] status = new int[] { 1, 2, 3,4, 6 };//DB定義的Status ID
            string[] disabled = new string[] { "3","6" };
            if (LoginState)
            {
                User member = GetMemberInfo();
                CoachService reserve = ReserveService.Instance.SearchService(member.MemberId, member.State)
                    .Where(c => c.OrderId.Equals(OrderId)).FirstOrDefault();
                var statusList = ReserveService.Instance.OrderStatusList(reserve.StatusId, status);
                statusList.Where(c => c.Value == "3").FirstOrDefault().Disabled = true;
                var model = new ServiceDetailModel()
                {
                    StatusList = new SelectList(statusList, "Value", "Text",reserve.StatusId, disabled),
                     Service= reserve

                };
                return View(model);
            }
            else
                return RedirectToAction("Login", "Home");
            
        }
        //會員檢視
        public ActionResult MemberServiceDetail(int OrderId=5)
        {
            
            int[] types = new int[] { 1, 2, 3,4,6 };
            if (LoginState)
            {
                User member = GetMemberInfo();

                CoachService reserve = ReserveService.Instance.SearchService(member.MemberId, member.State)
                    .Where(c => c.OrderId.Equals(OrderId)).FirstOrDefault();
                var status = ShareService.Instance.GetReserveStatus().Where(c => types.Contains(c.ID)).ToList();
                ServiceDetail model = new ServiceDetail()
                {
                    Service = reserve,
                    Status = status

                };

                return View(model);
            }
            else
                return RedirectToAction("Login", "Home");




        }
        [HttpPost]
        public ActionResult UpdateService(UpdateServicePara para)
        {
            
            var result = ReserveService.Instance.UpdateServiceOrder(para);
            return Json(new { success = result.ReturnNo == 1 ? true : false, ex = result.Message },
                 JsonRequestBehavior.AllowGet);
            
        }

        #endregion
    }
}

FitnessCenter_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
      @Styles.Render("~/Content/css")
      @RenderSection("css", required: false)
    @Scripts.Render("~/bundles/modernizr")


    
    <script src="~/Scripts/jquery-3.3.1.min .js"></script>
    <link href="~/Content/jquery-ui.css" rel="stylesheet" />
    <script src="~/Scripts/vue.js"></script>
    <style>
    .selector-for-some-widget {
  box-sizing: content-box;
}
        .navbar,footer {
        background-color:#aae5d2;
        color:#00284D;
        
        position:relative;
        
        }
        
       
        a {
        color:#00284D;
        }
        .dropdown-menu {
        min-width:8rem;
        
        }
    </style>
    <script type="text/javascript">

     

    </script>
</head>
<body>
   
    <nav class="navbar navbar-expand-lg">
        <a class="navbar-brand" href="@Url.Action("Index","Home")">Fitness Center</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

                @*<li class="nav-item">
                        <a class="nav-link" href="#">Features</a>
                    </li>*@
                @if ((bool)TempData["LoginState"] == true)
                {
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Search","Home")">教練列表</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="MemberCenter" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            會員中心
                        </a>
                        <div class="dropdown-menu" aria-labelledby="MemberCenter">
                            @if ((int)TempData["State"] == 0)
                            {
                                <a class="dropdown-item" href="@Url.Action("UpdateMember", "Member")">修改會員資料</a>
                            }
                            else
                            {
                                <a class="dropdown-item" href="@Url.Action("UpdateCoach", "Coach")">修改會員資料</a>
                            }
                            <a class="dropdown-item" href="@Url.Action("OrderList", "Reserve")">我的預約</a>
                            

                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Logout","Home")">登出</a>
                    </li>
                    <li class="nav-item">
                        <p class="nav-link">Hi,@TempData["UserName"] </p>
                    </li>
                   
                }
                else
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            註冊
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="@Url.Action("Register", "Member")">成為學員</a>
                            <a class="dropdown-item" href="@Url.Action("Register", "Coach")">教練登錄</a>

                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Login","Home")">登入</a>
                    </li>
                }
                

            </ul>
        </div>
    </nav>
    
   @RenderBody()

    <!-- Footer -->
    <footer class="page-footer font-small teal pt-4">

        <!-- Footer Text -->
        <div class="container-fluid text-center text-md-left">

            <!-- Grid row -->
            <div class="row">

                <!-- Grid column -->
                <div class="col-md-12 mt-md-0 mt-3" style="text-align:center;">

                    <!-- Content -->
                    <h5 class="text-uppercase font-weight-bold">Fitness Center自由教練媒合平台</h5>
                    <p>Blog | 粉絲專頁 | 教練列表 | 服務條款 | 隱私權政策 | 常見問題</p>

                </div>
                <!-- Grid column -->

                <hr class="clearfix w-100 d-md-none pb-3">


            </div>
            <!-- Grid row -->

        </div>
        <!-- Footer Text -->
        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">
            © 2019 Copyright:
            <a href="https://github.com/shadow061103?tab=repositories">kuanfitness.com</a>
        </div>
        <!-- Copyright -->

    </footer>
    <!-- Footer -->


    <script src="~/Scripts/popper.min.js"></script>
    
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    <script src="~/Scripts/jquery.multi-select.js"></script>

    
    @RenderSection("scripts", required: false)
</body>
</html>