FitnessCenter_Project/Controllers/CoachSearchController.cs
using FitnessCenter_Project.Service;
using FitnessCenterModel.Para;
using FitnessCenterModel.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using FitnessCenterModel.DTO;
namespace FitnessCenter_Project.Controllers
{
    //搜尋教練列表&教練資料
    public class CoachSearchController : baseController
    {
        Service.SearchService service = new Service.SearchService();
        private const int PageSize = 6;//每頁呈現筆數
       [HttpPost]
        public ActionResult CoachList(CoachListViewModel model)
        {
            //頁面dropdownlist
            model.AreaList =new SelectList(service.GetCountry(),"Value","Text");
            model.TrainingProgramList = new SelectList(service.GetTrainingProgramList(), "Value", "Text");
            model.CourseList = new SelectList(service.GetCourseList(), "Value", "Text");

            //search
            int pageIndex = model.PageIndex < 1 ? 1 : model.PageIndex;
            var list = new List<CoachData>();
            list= service.GetCoachList(model.searchPara);
            model.coachList = list.OrderBy(c => c.Name).ToPagedList(pageIndex, PageSize);
            
            return View(model);
        }
        public async System.Threading.Tasks.Task<ActionResult> CoachDetail(string MemberId = "17bc479ef762413fac09584de2a1c65e")
        {


            Coach coach = new Coach();
            coach = service.GetCoachDetail(MemberId);
            Location location = await service.TransAddressToLocation(coach.Address);
            CoachDetailViewModel model = new CoachDetailViewModel()
            {
                coach = coach,
                location = location
            };

            return View(model);
        }




    }
}

FitnessCenter_Project/Controllers/HomeController.cs
using FitnessCenter_Project.Service;
using FitnessCenterModel;
using FitnessCenterModel.DTO;
using FitnessCenterModel.Para;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace FitnessCenter_Project.Controllers
{
    public class HomeController : baseController
    {
        //首頁
        public ActionResult Index()
        {
            return View();
        }
        #region 搜尋
        public ActionResult Search()
        {
            return View();
        }
       
       
        #endregion

        #region 登入
        public ActionResult Login()
        {

            //自動登入做在這
            if (HttpContext.User.Identity.IsAuthenticated) //判斷是否已經登入
                return Redirect(FormsAuthentication.DefaultUrl);

            return View();
        }
        [HttpPost]
        public ActionResult LoginUser(LoginModel model)
        {
            LoginService service = new LoginService();
            LoginResult<User> result = service.Login(model);
            DateTime expireDate = model.autoLogin ? DateTime.Now.AddMonths(1) : DateTime.Now.AddMinutes(60);
            //登入成功
            if (result.ReturnNo == 1)
            {
                //登入ticket

                FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(1,
                    result.Memberinfo.Email,
                    DateTime.Now,
                    expireDate,
                    false,//是否將 Cookie 設定成 Session Cookie，如果是則會在瀏覽器關閉後移除
                    JsonConvert.SerializeObject(result.Memberinfo));

                var encTicket = FormsAuthentication.Encrypt(ticket);

                //FormsAuthentication.RedirectFromLoginPage(result.Memberinfo.Email, bPersistentCookie);
                //若設定為 true ，則 Cookie 資訊會儲存在 Client 端的磁碟中，有效期限預設為 30 分鐘；
                // 若設定為 false ，則 Cookie 資訊只會存放在 Client 端瀏灠器的記憶體中，所以則當使用者關閉瀏灠器後， Cookie 就會失效
                FormsAuthentication.SetAuthCookie(result.Memberinfo.Email, true);
                Response.Cookies.Add(
                       new HttpCookie(FormsAuthentication.FormsCookieName, encTicket));

            }

            return Json(new { success = result.ReturnNo == 1 ? true : false, ex = result.Message },
                JsonRequestBehavior.AllowGet);

        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Clear();
            TempData.Clear();
            return RedirectToAction("Login", "Home");
        }
        #endregion
        public ActionResult Test()
        { //測試google map
            return View();

        }
        public ActionResult Test2()
        {//好幾個marker
            return View();

        }
        public ActionResult Test3()
        {//json 加載數據到amp
            return View();
        }
    }
}

FitnessCenter_Project/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FitnessCenterModel;
using FitnessCenter_Project.Service;
using FitnessCenterModel.DTO;
using System.Net.Http;
using Newtonsoft.Json;
using System.Text;
using System.Web.Security;
using FitnessCenterModel.ViewModel;
using System.IO;

namespace FitnessCenter_Project.Controllers
{
    public class MemberController : baseController
    {
        
        public ActionResult Register()
        {
            return View();
        }
        //ajax方法
        [HttpPost]
        public ActionResult RegisterMember(RegisterMebmberViewModel model)
        {
            RegisterSerivce service = new RegisterSerivce();
            RegisterResult result = service.RegisterMember(model);
            return Json(new { success = result.ReturnNo==1? true:false,ex=result.Message },
                 JsonRequestBehavior.AllowGet);
        }

        public ActionResult UpdateMember()
        {
            UpdateService service = new UpdateService();
            UpdateMemberViewModel model = new UpdateMemberViewModel();
            //檢查是否登入狀態
            if (LoginState)
            {
                string City = string.Empty;
                string Area = string.Empty;
                string Address = string.Empty;
                User user = GetMemberInfo();
                string MemberId = user.MemberId;

                UpdateMember updatemodel = service.GetMemberInfo(MemberId);
                string[] AddressArray = updatemodel.User.Address.Split('|');
                if (AddressArray.Length == 3)
                {
                     City = AddressArray[0];
                     Area = AddressArray[1];
                    updatemodel.User.Address = AddressArray[2];
                }
                
                
                model.addressCity = City;
                model.addressArea = Area;
                model.addressCityList = new SelectList(service.GetCity(City), "Value", "Text");
                model.addresAreaList = new SelectList(service.GetArea(), "Value", "Text", Area);
                model.AreaList = new MultiSelectList(service.GetCity(updatemodel.OriginArea.ToArray()), "Value", "Text", updatemodel.OriginArea);
                model.UpdateModel = updatemodel;

            }
            else
               return RedirectToAction("Login", "Home");


            return View(model);

        }
        //ajax方法
        [HttpPost]
        public ActionResult UpdateMember(UpdateMemberViewModel model)
        {
            UpdateService service = new UpdateService();
            Result result = service.UpdateMember(model);

            return Json(new { success = result.ReturnNo == 1 ? true : false, ex = result.Message },
                  JsonRequestBehavior.AllowGet);
        }

        



    }
}

FitnessCenter_Project/Controllers/baseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FitnessCenterModel.DTO;
using System.Web.Security;
using Newtonsoft.Json;
using FitnessCenterModel;
using FitnessCenter_Project.Service;
namespace FitnessCenter_Project.Controllers
{
    public class baseController : Controller
    {
        protected bool LoginState { get; set; }
        // GET: base
        public User GetMemberInfo()
        {
            var user = HttpContext.User;
            if (user.Identity.IsAuthenticated)
            {
                
                var identity = (FormsIdentity)user.Identity;
                //取得 FormsAuthenticationTicket
                var ticket = identity.Ticket;
                return JsonConvert.DeserializeObject<User>(ticket.UserData);
            }
            return null;


        }
        //進action前檢查
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            //判斷有無登入
            if (filterContext.HttpContext.User.Identity.IsAuthenticated)
            {
                User user = GetMemberInfo();
                TempData["UserName"] = user.Name;
                TempData["State"] = user.State;
                LoginState = true;
               
            }
            else
                LoginState = false;
                
            
            TempData["LoginState"] = LoginState;


        }
        //地區列表 for ajax
        [HttpPost]
        public ActionResult GetCountryList()
        {
            
            var result = ShareService.Instance.GetCountry();
            var list = result.Distinct(c => c.City).Select(c => c.City).ToList();
            return Json(list, JsonRequestBehavior.AllowGet);

        }
        /// <summary>
        /// 第二層下拉選單 連動地區
        /// </summary>
        /// <param name="City"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetArea(string City)
        {
            
            var result = ShareService.Instance.GetCountry();
           var list = result.Where(c => c.City == City).Distinct(c => c.Area).Select(c => c.Area).ToList();
            return Json(list, JsonRequestBehavior.AllowGet);

        }
        /// <summary>
        /// 訓練項目
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetTrainingProgramList()
        {
            
            var result = ShareService.Instance.GetTrainingProgram();
            return Json(result, JsonRequestBehavior.AllowGet);

        }
        /// <summary>
        /// 課程形式
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetCourseList()
        {
            
            var result = ShareService.Instance.GetCourse();
            return Json(result, JsonRequestBehavior.AllowGet);

        }
    }
}

FitnessCenter_Project/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section css
{
    <style>
        .ad {
        margin-bottom:0rem;
        background-color:#fffbee;
        margin-left:auto;
        margin-right:auto;
        }
    </style>
    }
<div class="container">
    <div class="row">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="~/Image/stock-photo-a-strong-athletic-woman-sprinter-running-on-black-background-wearing-in-the-sportswear-fitness-748655305.jpg" />
                    
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="~/Image/stock-photo-athlete-woman-in-running-start-pose-on-the-city-street-sport-tight-clothes-bright-sunset-blurry-593935445.jpg" />
                    
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="~/Image/stock-photo-sport-backgrounds-sprinter-on-the-start-line-of-the-track-befor-the-dramatic-sky-603198743.jpg" />
                    
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <div class="row ad">
        <div class="jumbotron ad">
            <h2 class="display-4 text-primary">Fitness Center Propose</h2>
            <p class="lead">Animal Flow｜美國動物流地力訓練證照研習</p>
            <hr class="my-4">
            <p>研習日期：2019.3.2-3 </p>
            <p>
                研習地點：高雄-心運動體能訓練中心
            </p>
            <p>
                講師： Alisha Smith 澳洲動物流簽約國際講師
            </p>
            <p><strong>適合族群：體適能教練/ 團體課程老師/ 靜態課程老師/ 喜愛身體重量與自主訓練的所有人</strong></p>
            <p class="lead">
                <a class="btn btn-primary btn-lg" href="#" role="button">課程報名</a>
            </p>
        </div>


    </div>
</div>

FitnessCenter_Project/Views/Home/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section css
{
    <style>
        a:hover {
        text-decoration:none;
        
        }
        .container {
        min-height:750px;
        }
    </style>
    }

<div class="container" id="app">
    <div v-show="error" class="alert alert-danger alert-dismissible fade show" role="alert">

        <p>{{errorMsg}}</p>
        <button type="button" class="close"  aria-label="Close" v-on:click="closeAlert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <form action="@Url.Action("Login")" method="post" >
        <div class="row">
            <div class="offset-sm-3 col-sm-6">
                <h2>登入</h2>
                <hr />
            </div>
        </div>
        
        <div class="row form-group">
            <div class="offset-sm-3 col-sm-6">
                <label>帳號</label>
                <input type="text" class="form-control" v-model="model.Email" name="Email" placeholder="請輸入Email" />
                
            </div>
        </div>
        <div class="row form-group">
            <div class="offset-sm-3 col-sm-6">
                <label>密碼</label>
                <input type="password" class="form-control" v-model="model.Password" name="Password" placeholder="請輸入密碼" />
            </div>
        </div>
        <div class="row form-group">
            <div class="offset-sm-3 col-sm-6">
                <label>你是</label>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="State" v-model="model.State" value="0" checked>
                    <label class="form-check-label" for="State">
                        學員
                    </label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="State"  v-model="model.State" value="1">
                    <label class="form-check-label" for="State">
                        教練
                    </label>
                </div>
                
            </div>

        </div>
        <div class="row form-group">
            <div class="offset-sm-3 col-sm-6">
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" v-model="model.autoLogin" id="autoLogin">
                    <label class="form-check-label" for="autoLogin">
                        下次自動登入
                    </label>
                </div>
            </div>

        </div>
        <div class="row form-group">
            <div class="offset-sm-3 col-sm-6">
                <button type="button" v-on:click="Login" class="btn btn-outline-primary btn-lg btn-block">登入</button>
            </div>

        </div>
        <div class="form-row text-center hyper">
            
            <div class="offset-sm-3 col-sm-3">
                <a href="#">忘記密碼</a>
            </div>
            <div class="col-sm-3">
                <a href="@Url.Action("Register","Member")">註冊</a>
            </div>
        </div>
        <br/>

    </form>

    

    
</div>

@section scripts
{
    <script type="text/javascript">

        var instance = {
            Email:'',
            Password:'',
            State:0,
            autoLogin:false

        }

        var app = new Vue({
            el:'#app',
            data: {
                model: instance,
                errorMsg:'',
                error:false
            },
            methods: {
                Login: function () {
                    $.ajax({
                        type: "POST",
                        url: "@Url.Action("LoginUser", "Home")",
                        contentType: "application/json;charset=utf-8",
                        datatype: "json",
                        data: JSON.stringify(app.model),
                        success: function (data)
                        {


                            if (data.success) {
                                console.log('success');
                                window.location.href = '@Url.Action("Index","Home")';
                            }
                            else {
                                console.log(data.ex);
                                app.errorMsg = data.ex;
                                console.log('app.errorMsg' + app.errorMsg);
                                app.error = true;

                            }
                        },
                        error: function (ex)
                        {

                            alert(ex.Message);
                        }

                    });


                },
                closeAlert: function () {
                    app.error = false;

                }
            }


        });


    </script>
    }

FitnessCenter_Project/Views/Home/Search.cshtml
@model FitnessCenterModel.ViewModel.CoachListViewModel

@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section css
{
    <style>

        #top {
            background-image: url('../../Image/Fitnessgirl.jpg');
           background-repeat: no-repeat;
            height: 700px;
            width: 100%;
            background-size: cover;
            background-position: center;
            background-attachment: fixed;
        }
        .container {
        max-width:100%;
        background-color:#E0FFFF;
        }
        .box {
        position:absolute;
        top:50%;
        left:50%;
        margin: -150px 0 0 -600px;
        width: 1200px;
        height: 300px;
        }
    </style>
}
<div class="container ">
    
    <div id="top">
        <div class="box">
            <form action="@Url.Action("CoachList", "CoachSearch")" method="post">

                <div class="row form-group">
                    <div class="offset-sm-3 col-sm-6">
                        <select class="form-control" id="searchPara_TrainingProgramId" name="searchPara.TrainingProgramId">
                            <option value="0" selected>請選擇訓練項目</option>
                        </select>

                    </div>
                </div>
                <div class="row form-group">
                    <div class="offset-sm-3 col-sm-6">
                        <select class="form-control" id="searchPara_CourseId" name="searchPara.CourseId">
                            <option value="0" selected>請選擇課程形式</option>
                        </select>

                    </div>
                </div>
                <div class="row form-group">
                    <div class="offset-sm-3 col-sm-6">
                        <select class="form-control" id="searchPara_Area" name="searchPara.Area" >
                            <option value="" selected>請選擇上課地區</option>
                        </select>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="offset-sm-3 col-sm-6">
                        <button type="submit" class="btn btn-primary btn-lg btn-block">主動搜尋教練</button>
                    </div>
                </div>

            </form>
        </div>
       
    </div>
        
 
    
</div>
@section scripts{
    <script type="text/javascript">

        $(function () {
            GetCountry();
            GetProgram();
            GetCourse();
        });

        function GetCountry() {
            $.ajax({
                type: "POST",
                url: "@Url.Action("GetCountryList", "base")",
                contentType: "application/json;charset=utf-8",
            datatype: "json",
            success: function (data) {
                $.each(data, function (index, value) {
                    $('#searchPara_Area').append($("<option></option>").attr("value", value).text(value));
                    
                });
               
            },
            error: function (ex) {

            }

        });
        }
        function GetProgram() {
            $.ajax({
                type: "POST",
                url: "@Url.Action("GetTrainingProgramList", "base")",
                contentType: "application/json;charset=utf-8",
            datatype: "json",
            success: function (data) {
                $.each(data, function (index, item) {

                    $('#searchPara_TrainingProgramId').append($("<option></option>").attr("value", item.ID).text(item.TrainingProgram));
                });
                


            },
            error: function (ex) {

            }

        });
        }
        function GetCourse() {
            $.ajax({
                type: "POST",
                url: "@Url.Action("GetCourseList", "base")",
                contentType: "application/json;charset=utf-8",
            datatype: "json",
            success: function (data) {

                $.each(data, function (index, item) {

                    $('#searchPara_CourseId').append($("<option></option>").attr("value", item.ID).text(item.Course));
                });
               
            },
            error: function (ex) {

            }

        });
        }
    </script>
    
    }

FitnessCenter_Project/Views/Home/Test.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Test</title>
    <style>
        html{
	height: 100%;
	width: 100%;
}
#body{
	position: relative;	/*相對定位*/
	height: 100%;
	width: 100vw;
	top: 0;
	left: 0;
}
#map {
	position: absolute;
	top: 25%;	/*地圖佔頁面的3/4，即 頁面高 - 地圖高 = 定位點高度 (100%-75%=25%) */
	left: 0;
    height: 75%;	/*地圖高*/
    width: 100vw;
}
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
</head>
<body>
    
    <div class="body">
        <h1>King Tzeng的鐵人地圖</h1>
        <div id="map"></div>
    </div>
    <script>
        function initMap() {
            var Station_latlng = { lat: 25.064385, lng: 121.575554 };	// 台北車站的經緯度
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 14,	//放大的倍率
                center: Station_latlng	//初始化的地圖中心位置
            });

            //--------下面是呼叫一個新marker------

            var marker = new google.maps.Marker({
                position: Station_latlng,	//marker的放置位置
                icon: 'https://maps.google.com/mapfiles/kml/shapes/parking_lot_maps.png',
                map: map //這邊的map指的是第四行的map變數
            });
            //獲取當前位置
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function (position) {
                    var pos = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                    };
                    var marker = new google.maps.Marker({
                        position: pos,
                        icon: 'marker.png',
                        map: map
                    });
                    map.setZoom(17);
                    map.setCenter(pos);
                });
            } else {
                // Browser doesn't support Geolocation
                alert("未允許或遭遇錯誤！");
            }

        }
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=yourkey&callback=initMap">
    </script>
</body>
</html>

FitnessCenter_Project/Views/Home/Test2.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Test2</title>
    <style>
         /* Always set the map height explicitly to define the size of the div
        * element that contains the map. */
         #map {
             height: 100%;
         }
         /* Optional: Makes the sample page fill the window. */
         html, body {
             height: 100%;
             margin: 0;
             padding: 0;
         }
    </style>
</head>
<body>
    <div id="map"> 
    </div>
    <script>

      function initMap() {

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 3,
          center: {lat: -28.024, lng: 140.887}
        });

        // Create an array of alphabetical characters used to label the markers.
        var labels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

        // Add some markers to the map.
        // Note: The code uses the JavaScript Array.prototype.map() method to
        // create an array of markers based on a given "locations" array.
        // The map() method here has nothing to do with the Google Maps API.
          //locations.map = Array.prototype.map()
        var markers = locations.map(function (location, i) {
          return new google.maps.Marker({
            position: location,
            label: labels[i % labels.length]
          });
        });

        // Add a marker clusterer to manage the markers.
        var markerCluster = new MarkerClusterer(map, markers,
            {imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'});
      }
      var locations = [
        {lat: -31.563910, lng: 147.154312},
        {lat: -33.718234, lng: 150.363181},
        {lat: -33.727111, lng: 150.371124},
        {lat: -33.848588, lng: 151.209834},
        {lat: -33.851702, lng: 151.216968},
        {lat: -34.671264, lng: 150.863657},
        {lat: -35.304724, lng: 148.662905},
        {lat: -36.817685, lng: 175.699196},
        {lat: -36.828611, lng: 175.790222},
        {lat: -37.750000, lng: 145.116667},
        {lat: -37.759859, lng: 145.128708},
        {lat: -37.765015, lng: 145.133858},
        {lat: -37.770104, lng: 145.143299},
        {lat: -37.773700, lng: 145.145187},
        {lat: -37.774785, lng: 145.137978},
        {lat: -37.819616, lng: 144.968119},
        {lat: -38.330766, lng: 144.695692},
        {lat: -39.927193, lng: 175.053218},
        {lat: -41.330162, lng: 174.865694},
        {lat: -42.734358, lng: 147.439506},
        {lat: -42.734358, lng: 147.501315},
        {lat: -42.735258, lng: 147.438000},
        {lat: -43.999792, lng: 170.463352}
      ]
    </script>
    <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js">
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=yourkey&callback=initMap">
    </script>
</body>
</html>

FitnessCenter_Project/Views/Home/Test3.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <title>Test3</title>
    <style>
         /* Always set the map height explicitly to define the size of the div
        * element that contains the map. */
         #map {
             height: 100%;
         }
         /* Optional: Makes the sample page fill the window. */
         html, body {
             height: 100%;
             margin: 0;
             padding: 0;
         }
    </style>
</head>
<body>
    <div id="map"> 
    </div>
    <script>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 2,
          center: new google.maps.LatLng(2.8,-187.3),
          mapTypeId: 'terrain'
        });

        // Create a <script> tag and set the USGS URL as the source.
        var script = document.createElement('script');
        // This example uses a local copy of the GeoJSON stored at
        // http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_week.geojsonp
        script.src = 'https://developers.google.com/maps/documentation/javascript/examples/json/earthquake_GeoJSONP.js';
        document.getElementsByTagName('head')[0].appendChild(script);
      }

      // Loop through the results array and place a marker for each
      // set of coordinates.
      window.eqfeed_callback = function(results) {
        for (var i = 0; i < results.features.length; i++) {
          var coords = results.features[i].geometry.coordinates;
          var latLng = new google.maps.LatLng(coords[1],coords[0]);
          var marker = new google.maps.Marker({
            position: latLng,
            map: map
          });
        }
      }
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=yourkey&callback=initMap">
    </script>
</body>
</html>